version: '3.8'

services:
  backend:
    build: ./backend
    container_name: online-shop-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/onlineshop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - APP_UPLOAD_DIR=/app/images
    volumes:
      - "C:/Murtuza-dDrive/MCube/DBohraMartSite:/app/images"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: online-shop-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
