spring.application.name=backend
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/onlineshop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload limits (Increased to 10MB to allow high-quality promotions)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom App Configuration
app.base-url=https://scroll-contained-particularly-rochester.trycloudflare.com
app.frontend-url=http://localhost,http://127.0.0.1,http://192.168.0.105,https://expertise-modifications-voip-interim.trycloudflare.com
app.upload.dir=C:/Murtuza-dDrive/MCube/DBohraMartSite

# CORS (To allow React frontend to connect)
spring.mvc.cors.allowed-origin-patterns=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true
